server.port: 8081
server.servlet.context-path: /springBoot

spring:
  datasource:
    url: jdbc:mysql://8.140.168.210:3306/test?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.springboot.entity
  configuration-properties: log-impl:org.apache.ibatis.logging.stdout.StdOutImpl

author:
  name: Xiao隋
  sex: 男